exclude_paths:
- "source/common/javascript/common/bootstrap/*"
- "source/common/javascript/common/codemirror/*"
- "source/common/javascript/common/jquery/*"
- "source/common/javascript/generated/beautify/beautify.js"
languages:
  JavaScript: true
